using System;
using CAPSTONE_Swift_Server;
using Microsoft.EntityFrameworkCore;
using CAPSTONE_Swift_Server.Models;
using System.Diagnostics.Metrics;
using System.Reflection.Emit;

namespace CAPSTONE_Swift_Server
{
	public class SwiftDbContext : DbContext
	{
		public DbSet<User> Users { get; set; }
		public DbSet<Order> Orders { get; set; }
		public DbSet<Product> Products { get; set; }
		public DbSet<Review> Reviews { get; set; }
		public DbSet<Cart> Carts { get; set; }
        public DbSet<Newsletteruser> NewsletterUsers { get; set; }

        public SwiftDbContext(DbContextOptions<SwiftDbContext> context) : base(context)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // seed data with campsite types
            modelBuilder.Entity<User>().HasData(new User[]
            {
                new User { Id = 1, CustomerUid = "zcxxFyDPReWizoUPtyPru9w072J3", Name = "Jovanni Feliz", Email = "feliz.jovanni@gmail.com", PhoneNumber = 6037779999, IsAdmin = true },
                new User { Id = 2, CustomerUid = "p84DEdgj4kYhU4VKJfFqZX7unHD3", Name = "John Mahlar", Email = "MahlJ@gmail.com", PhoneNumber = 4324566788, IsAdmin = false },
            });

            modelBuilder.Entity<Product>().HasData(new Product[]
            {
                new Product { Id = 1, AdminId = 1, Title = "AXIS 37", Description = "A snowboard-inspired drop-through for easy around town cruising, relaxed commutes, and mellow downhill.", Category = "cruiser", Price = 119.99, Length = 37, Width = 8.5, Wheelbase = 119.99, SkateSpots = "Pathways, Campus, Mellow Hills",ImageUrl1 = "https://i.pinimg.com/originals/0a/f1/e8/0af1e8171aab8cd9fc0e4a295985dce2.jpg", ImageUrl2 = "https://i.pinimg.com/originals/48/be/75/48be75c292691c6eec0e1da8667c344f.jpg", ImageUrl3 = "https://i.pinimg.com/originals/b2/5f/8b/b25f8baa13db7db1900ba3e72de1c585.jpg" },
                new Product { Id = 2, AdminId = 1, Title = "ARBOR - MISSION", Description = "A single-kick carver designed to be agile for all of your out-and-about missions.", Category = "carving", Price = 89.99, Length = 35, Width = 8.625, Wheelbase = 21.375, SkateSpots = "Pathways, Campus, Mellow Hills",ImageUrl1 = "https://i.pinimg.com/originals/dd/84/f0/dd84f0ccf90a2fdf4570e82f78b288d2.jpg", ImageUrl2 = "https://i.pinimg.com/originals/69/b6/e4/69b6e4cd8827f984c4da336ae3cb8b4c.jpg", ImageUrl3 = "https://i.pinimg.com/originals/39/82/36/398236d715803f6c04bbdd11935a0dc5.jpg" },
                new Product { Id = 3, AdminId = 1, Title = "DIPPER - FISH", Description = "The Dipper is a pintail designed to bring the compact maneuverability of a cruiser board to a carvy, flexy longboard shape. This board gives you a tight-turning, responsive ride that will make weekday commutes or casual weekend cruises the highlight of your week. The narrow width provides you with incredible control over the edges of the board so you can ride this thing aggressively if you want to or take it easy on those casual cruises. Mellow concave and a subtle rocker will have you feeling right at home on this board. Often referred to as the “best board ever” at skate sessions.", Category = "cruiser", Price = 169.99, Length = 36, Width = 8.65, Wheelbase = 24.29, SkateSpots = "Pathways, Campus, Mellow Hills", ImageUrl1 = "https://media.rainpos.com/3226/Screenshot_2023_05_31_at_16_49_06_Dipper_Fish.png", ImageUrl2 = "https://i.pinimg.com/originals/37/27/b7/3727b77e532fd1ab491746b3142c75c6.jpg", ImageUrl3 = "https://www.flatspotlongboards.com/wp-content/uploads/landyachtz-longboards-dipper-fish-complete-cruiser-2-600x600.jpg" },
                new Product { Id = 4, AdminId = 1, Title = "SWITCHBLADE 40 - CHIEF NIGHTK", Description = "Designed to rally big mountain terrain and conquer World Cup podiums, the Switchblade has proven itself equally adept at getting you to the grocery store and ripping down your local hill safely. The mellow drops, long wheelbase and low ride height combine to offer a drifty, confidence-inspiring feel perfect for riders looking to up their freeride game. The Switchblade 40 is the longer version, offering a more stable ride and slightly easier slide initiation, as well as being a bit more comfortable for taller riders.", Category = "carving", Price = 169.99, Length = 40, Width = 10, Wheelbase = 31, SkateSpots = "City, Alley, Path, Campus, Hill, Mountain",ImageUrl1 = "https://landyachtz.com/cdn/shop/files/landyachtz-switchblade-night-40--Graphic-WEB_1200x1200.jpg?v=1683932973", ImageUrl2 = "https://i.pinimg.com/originals/13/89/75/13897541811396e5692f28f3e5c35ebf.jpg", ImageUrl3 = "https://i.pinimg.com/originals/d0/c9/f3/d0c9f398a8226c52fb8162dce3525d0c.jpg" },
                new Product { Id = 5, AdminId = 1, Title = "DROP CAT 38 - SEEKER BLACK", Description = "Time-tested maple construction and super low ride height come together with a futuristic rocker profile to create a board that lets you travel through time to sample the very best of what we've learned over 20-plus years of designing boards. The Drop Cat 38 is perfect for taller riders or people looking for a more stable ride.", Category = "cruiser", Price = 212.49, Length = 38.6, Width = 9.9, Wheelbase = 29.3, SkateSpots = "Pathways, Campus, Mellow Hills",ImageUrl1 = "https://landyachtz.com/cdn/shop/products/Drop-Cat-38-Black-Seeker-Graphic-WEB_b7086e12-107a-4631-8b8e-f0658f0a4088_1800x1800.jpg?v=1614532582", ImageUrl2 = "https://i.pinimg.com/originals/4f/fa/be/4ffabe532b54792e769e0aba458e0639.jpg", ImageUrl3 = "https://i.pinimg.com/originals/d0/c9/f3/d0c9f398a8226c52fb8162dce3525d0c.jpg" },
                new Product { Id = 6, AdminId = 1, Title="EVO 40 - SPECTRUM", Description="A pillar of the Landyachtz DH line for over a decade, the Evo has been under the feet of 3 World Champions as well as countless race winners and podium contenders. The Evo 40 offers a drifty and stable ride that will fill any day in the hills with casually fast runs.", Category="downhill", Price=259.99 , Length=39, Width=9.8, Wheelbase=31.7, SkateSpots="Hill, Mountain, Race Track", ImageUrl1="https://landyachtz.com/cdn/shop/products/Evo-40-Spectrum-Alt-Setup-WEB-Graphic_1800x1800.jpg?v=1628815758", ImageUrl2="https://landyachtz.com/cdn/shop/products/Evo-40-Spectrum-Alt-Setup-WEB-Grip_1800x1800.jpg?v=1628815758", ImageUrl3="https://landyachtz.com/cdn/shop/products/Evo-40-Spectrum-Alt-Cover-WEB-Angle-01_1800x1800.jpg?v=1628815758"},
                new Product { Id = 7, AdminId = 1, Title="BLAZE - PT", Description="Will it freeride? Obviously. Will it also grip? Heck yes! Clayton Arthurs is one of the most versatile members of the Landyachtz team and he wanted his pro board to be able to make the switch from race track to slide jam just as comfortably as he can. The Blaze is designed to be equally effective with small slalom trucks on it for tons of grip, or with 155mm symmetrical trucks and freeride wheels for huge standup slides.", Category="downhill", Price=299.99 , Length=34, Width=9, Wheelbase=23.7, SkateSpots="Pathways,Steep Hills, Big Mountain Road, all terrain", ImageUrl1="https://landyachtz.com/cdn/shop/products/122CP-DHCABC-BCCruiserskateboardgraphic_AD_4761-WEB_b00e1698-5cc0-4f79-bb20-e97ae05c4d55_1800x1800.jpg?v=1646115057", ImageUrl2="https://landyachtz.com/cdn/shop/products/122CP-DHCABC-BCCruiserskateboard4_AD_4787-WEB_3f68fa55-dce3-4f93-a0cc-8d3a50a0f4bd_1800x1800.jpg?v=1646115057", ImageUrl3="https://landyachtz.com/cdn/shop/products/122CP-DHCABC-BCCruiserskateboardwheeldown_AD_4769-WEB_8654a3fe-f1ef-4342-b733-4663fe4276e3_1800x1800.jpg?v=1646115057"},
                new Product { Id = 8, AdminId = 1, Title="DERVISH SAMA", Description="Designed as an intuitive carving and pumping board, the Dervish Sama longboard is low and easy to ride for both the first-time skater looking to cruise around town and the experienced rider seeking a soulful, snowboard-inspired ride and the ability to explore longboard dancing and freestyle.", Category="dance", Price=329.99 , Length=42.8, Width=9, Wheelbase=31.5, SkateSpots="Pathways, Campus, Mellow Hills", ImageUrl1="https://i.pinimg.com/originals/0e/6d/8b/0e6d8b6e9bdb667c04aee63db68388b3.jpg", ImageUrl2="https://i.pinimg.com/originals/2e/c0/6a/2ec06af82bfba88a3735f8221ab1c581.jpg", ImageUrl3="https://i.pinimg.com/originals/24/e9/ea/24e9eac8fba6ac11e71fef704eed6499.jpg"},
                new Product { Id = 9, AdminId = 1, Title="TARAB II", Description="Since 2008 Loaded has been on the forefront of longboard dancing. The Tarab II deepens our roots and seeks to advance modern longboard dancing through thoughtful design and material evolution. Ideal for riders who want a versatile and well-rounded platform for surfy boardwalking lines, smooth freestyle trickery, and everything in between.", Category="dance", Price=444.99 , Length=47, Width=9.5, Wheelbase=31.25, SkateSpots="Pathways, Campus, Mellow Hills", ImageUrl1="https://i.pinimg.com/originals/a8/64/9d/a8649dde4a3068cd5f6702d66c2594d9.jpg", ImageUrl2="https://i.pinimg.com/originals/f1/d7/66/f1d7662af21b042fa5f6585c367255da.jpg", ImageUrl3="https://i.pinimg.com/originals/f9/8c/cc/f98ccc037bdde63d8a5973608e7062cb.jpg"},
                new Product { Id = 10, AdminId = 1, Title="SWIFT CITY RIDER 3", Description="Dubbed City Rider 3 for its evolution in skateboarding, this masterpiece speaks to both new riders and seasoned enthusiasts. We understand that whether you're gliding on city asphalt or bustling streets, the allure of off-road skating remains. Safety, the essence of your experience, is ingeniously woven into the City Rider 3’s DNA. With large 150mm wheels and a wide truck long board, you’re equipped to conquer obstacles with confidence, and the enhanced stability makes each ride a testament to your secure journey.", Category="electric", Price=899.99 , Length=42.8, Width=9, Wheelbase=150, SkateSpots="Hill, Mountain, Race Track, all terrain", ImageUrl1="https://i.pinimg.com/originals/9e/01/65/9e016571a1630c54a2b9e82b5a89b50a.jpg", ImageUrl2="https://i.pinimg.com/originals/f4/10/9f/f4109fc8f6c82c6988378481d43bc535.jpg", ImageUrl3="https://i.pinimg.com/originals/ad/47/11/ad4711f25374e57ed42551144305b265.jpg"},
                new Product { Id = 11, AdminId = 1, Title="PINTAIL 43", Description="Dropped low, like the Apex 34 and Apex 37, the Pintail 43 is a plate special with all the fixins to satiate your longboard hunger. This tasty delicacy is 43 inches of medium rare satisfaction, served with a slight concave, and the finest graphic art au jus by Joe Hodnicki....", Category="pintail", Price=239.99 , Length=43, Width=9, Wheelbase=29.5, SkateSpots="Pathways, Campus, Mellow Hills", ImageUrl1="https://i.pinimg.com/originals/4d/d6/a4/4dd6a4f226b48bd1fd821a11894f6382.jpg", ImageUrl2="https://i.pinimg.com/originals/b7/43/6a/b7436a3ce8ead501ddbdbec9e0f9e06f.jpg", ImageUrl3="https://i.pinimg.com/originals/e0/7c/7f/e07c7f798ae36ab0fcd91048df964d4a.jpg"},
                new Product { Id = 12, AdminId = 1, Title="DERRINGER 33", Description="Our favorite mini-carver sprouted a kicktail, and things have never been the same. Let the Derringer 33 manual its way, your way, and straight into your heart with 3 killer new graphics. ", Category="pintail", Price=199.99 , Length=33, Width=9, Wheelbase=29.5, SkateSpots="Pathways, Campus, Mellow Hills", ImageUrl1="https://i.pinimg.com/originals/a9/ea/51/a9ea5143729dea0880631373aa34dd92.jpg", ImageUrl2="https://i.pinimg.com/originals/6b/86/c1/6b86c1bb639b977d0505f7a93ffafa41.jpg", ImageUrl3="https://i.pinimg.com/originals/23/4a/bf/234abf0e154cf07a6f034328e697ff15.jpg"},
                 new Product { Id = 13, AdminId = 1, Title="BASALT TESSERACT", Description="The Basalt Tesseract integrates dual kicktails, rocker, wheel well flares, W concave, and multiple wheelbase options into a lightweight package designed for hilly descents, snappy slides, lofty ollies, techy manual combos, and cross-steps galore.\r\n\r\nBuilding on our experience manufacturing the Tarab, we’ve updated the Basalt Tesseract with a high-performance, eco-conscious basalt fabric construction for a lighter, damper, and more freestyle-friendly longboard. Get lit with lava.", Category="freeride", Price=339.99 , Length=39, Width=9.5, Wheelbase=26, SkateSpots="Pathways, Campus, Mellow Hills, City Streets", ImageUrl1="https://i.pinimg.com/originals/bf/fe/9d/bffe9d224c84ac52587d1b72a0d3eecb.jpg", ImageUrl2="https://i.pinimg.com/originals/29/82/40/29824019a232aa44999002f44f2a6076.jpg", ImageUrl3="https://i.pinimg.com/originals/32/bc/e6/32bce6f106298434abd07290d078bc1c.jpg"},

                 new Product { Id = 14, AdminId = 1, Title="BIG DIPPER - MOUNTAIN", Description="The Big Dipper is like a magic carpet with wheels. Coming in at 42.2” long and boasting a healthy amount of flex, this is a longboard in the classic sense of the word. Because of its length, the Big Dipper is very forgiving to ride, whether you are a beginner learning to skate or someone trying to push the limits of what a flexy longboard can do. This beast is the perfect choice for anyone looking for a smooth & stable ride with lots of flow and surf style.", Category="beginner", Price=249.99 , Length=42.2, Width=9.48, Wheelbase=29.8, SkateSpots="Pathways, Campus, Mellow Hills, City Streets, Beach", ImageUrl1="https://landyachtz.com/cdn/shop/products/122CP-LBBDPMTN-BigDipperMountainskateboardgraphic_AD_4748-WEB_1800x1800.jpg?v=1651272223", ImageUrl2="https://landyachtz.com/cdn/shop/products/122CP-LBBDPMTN-BigDipperMountainskateboardgrip_AD_4749-WEB_1800x1800.jpg?v=1651272223", ImageUrl3="https://landyachtz.com/cdn/shop/products/122CP-LBBDPMTN-BigDipperMountainskateboardwheeldown_AD_4764-WEB_1800x1800.jpg?v=1651272223"},
            });

            modelBuilder.Entity<Order>().HasData(new Order[]
            {
                new Order { Id = 1, CustomerUid = "p84DEdgj4kYhU4VKJfFqZX7unHD3", Status = false, CustomerName = "John Mahlar", CustomerEmail = "MahlJ@gmail.com", CustomerPhoneNumber = 4324566788, StreetAddress = "431 Grove Ave", Country = "USA", TownCity = "Salt Lake City", State = "MS", Zipcode = 37205, DateTime = DateTime.Now, Revenue = 581.99, ShippingMethod = "Standard", PaymentType = "visa"},
            });

            modelBuilder.Entity<Review>().HasData(new Review[]
            {
                new Review { Id = 1, CustomerUid = "p84DEdgj4kYhU4VKJfFqZX7unHD3", Subject = "I approve!", Content = "I love this product!", Rating = 5 },
                new Review { Id = 2, CustomerUid = "p84DEdgj4kYhU4VKJfFqZX7unHD3", Subject = "Don't recommend! Bad Product.", Content = "The board was flimsy. Bad product.", Rating = 1 },
                new Review { Id = 3, CustomerUid = "p84DEdgj4kYhU4VKJfFqZX7unHD3", Subject = "Great purchase! Happy Customer", Content = "I bought one for my cousin and he loved it!!", Rating = 4 },
            });

            modelBuilder.Entity<Newsletteruser>().HasData(new Newsletteruser[]
            {
                new Newsletteruser { Id = 1, CustomerUid = "zcxxFyDPReWizoUPtyPru9w072J3", Email = "feliz.jovanni@gmail.com" }
            });
        }
                protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
 => optionsBuilder
     .UseNpgsql()
     .UseSnakeCaseNamingConvention();
    }
}
